### ISSUE TITLE
Incorrect doco

### ISSUE THREAD

**Issue by rowanwins** [nerik/formatcoords#1]
Thanks for a great little module, does exactly what I need!

I did have a smidge of trouble getting it going because the doco says 

```
formatcoords(40.76,-73.984).parse();
```

however I believe the correct approach is

```
formatcoords(40.76,-73.984).format();
```

If I've understood correctly then I'd be happy to submit and pull request with the documentation tidied up 

Cheers
Rowan

**Comment by nerik** [comment]
Hi Rowan,
Yes, that's a glitch in the docs, thanks for noticing.
I'm happy to review and merge a PR.
Thanks
