### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by tlareg** [nerik/formatcoords#6]
Hi! There is no license information.

**Comment by Krzysiu** [comment]
Hey! I know this isn't direct answer to the problem, which only author can solve, but as author didn't solve it yet, I'm giving what I've found: https://www.movable-type.co.uk/scripts/js/es6-geodesy/docs/dms.js.html - it's on MIT and it's lightweight. Some features are missing, some are extra. 

To remove leading padding from degrees, remove lines 122-123 and change in line 144 `lat.slice(1)` to `lat`

**Comment by nerik** [comment]
Fixed in https://github.com/nerik/formatcoords/commit/657d53ceb87fc48e83f6be8aaad7e241f9e60047
